### ISSUE TITLE
With deprecation of SignalAuthStateHandler, is there a way to use channels to send auth messages?

### ISSUE THREAD

**Issue by moonstripe** [aCLr/rust-tdlib#34]
I'm writing a Tauri app, which requires me to first input api_id and hash with a phone number ClientIdentified Client Auth system, and then later do the auth_code step.

Is it possible to accomplish this without using ConsoleClientAuth? The example in handle_auth_state uses the deprecated SignalAuthStateHandler, so I'm wondering if we can only authenticate from the command line.

**Comment by antonio-antuan** [comment]
You can write your own implementation of `crate::client::auth_handler::ClientAuthStateHandler` and use it instead of `ConsoleClientStateHandlerIdentified` for `ClientBuilder::with_client_auth_state_handler method`.

Anyway good note, better to have the same functionality so I'd like to present option with Signal-like handler. Hope to achive this in a several days.

**Comment by moonstripe** [comment]
All good, I'll experiment with implementing a custom ClientAuthStateHandler, and let you know if I run into any more issues.

Thanks, antonio!

Edit: Working like a charm. Again, thank you so much for your support with all of this! You're a huge help as always! Closing now.

**Comment by moonstripe** [comment]
closing!
